name: CI/CD - TP2 with ACR & ACA

on:
  push:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Build Docker image
        run: docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/tp2-cicd:latest .

      - name: Log in to ACR
        run: echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

      - name: Push Docker image
        run: docker push ${{ secrets.ACR_LOGIN_SERVER }}/tp2-cicd:latest

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Deploy to Azure Container Apps (staging)
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az containerapp update \
              --name aca-tp2-staging \
              --resource-group rg-tp2 \
              --image ${{ secrets.ACR_LOGIN_SERVER }}/tp2-cicd:latest

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to Azure Container Apps (prod)
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az containerapp update \
              --name aca-tp2-prod \
              --resource-group rg-tp2 \
              --image ${{ secrets.ACR_LOGIN_SERVER }}/tp2-cicd:latest
