name: Init ACR

on:
  workflow_dispatch:   # déclenchement manuel

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Build & Push Docker image
      run: |
        echo "${{ secrets.ACR_PASSWORD }}" | docker login acrtp2<initiales>.azurecr.io -u ${{ secrets.ACR_USERNAME }} --password-stdin
        docker build -t acrtp2<initiales>.azurecr.io/tp2-cicd:initial .
        docker push acrtp2<initiales>.azurecr.io/tp2-cicd:initial
